### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlphaKR93** [PrismarineTeam/Prismarine#4]
# Prismarine 1.19 To-do 로 이전됨

### Community Utils
- [ ] PR 템플릿 추가
- [ ] 패치 제작 및 기여 가이드라인 추가
- [ ] Contributor Covenant Code of Conduct 추가

### Server Changes
- [ ] [Patina](https://github.com/PatinaMC/Patina) 패치 추가
   - [x] Server Changes
   - [x] API Changes
   - [ ] [EmpireCraft](https://github.com/starlis/empirecraft)
      - [x] Server Changes
      - [ ] Server Changes (API Support)
      - [ ] API Changes
   - [ ] [Jettpack](https://gitlab.com/Titaniumtown/JettPack)
      - [ ] Server Changes
      - [ ] API Changes
- [ ] All [Paper PRs](https://github.com/PaperMC/Paper/pulls)
