### ISSUE TITLE
Prismarine 1.19 To-do

### ISSUE THREAD

**Issue by AlphaKR93** [PrismarineTeam/Prismarine#8]
### Github
- [x] README.md 정리
- [ ] Code of Conduct 추가
- [ ] 기여 가이드 추가
- [ ] Prismarine 기반 커스텀 버킷 템플릿 및 위키 추가
- [ ] 위키 탭 추가 (구성 파일)

### Main
- [x] 1.19로 업데이트
   - [x] API 패치
   - [x] 서버 패치
- [x] PrismarineManager 업데이트
   - [x] 1.19 지원 추가
   - [x] Gradle Wrapper 업데이트 재추가
   - [x] 커밋 설명에서 업스트림 커밋이 제대로 라인 변경 되지 않는 오류 해결
   - [x] 커밋 설명에서 업스트림 커밋이 한칸 뒤에 입력되는 오류 해결
   - [ ] 커밋시 모든 업스트림의 커밋이 CI를 스킵하면 커밋 앞 접두사로 `[CI-Skip]` 을 추가하도록 변경
- [x] [Patina](https://github.com/PatinaMC/Patina) 패치 재추가
   - [x] 서버 패치
   - [x] API 패치
- [x] [Akarin](https://github.com/Akarin-project/Akarin) 패치 추가
   - [x] 서버 패치
- [ ] [Jettpack](https://gitlab.com/Titaniumtown/JettPack) 패치 추가
   - [ ] 서버 패치 (21개 남음)
   - [x] API 패치
- [ ] [Slice](https://github.com/Cryptite/Slice) 패치 추가
   - [ ] 서버 패치
      - [ ] 일반 (2개 남음)
      - [ ] API
   - [ ] API 패치
- [ ] [Empirecraft](https://github.com/starlis/empirecraft) 패치 재추가
   - [ ] 서버 패치
      - [ ] API
      - [ ] 일반
   - [ ] API 패치

### Later
- [ ] 게임 플레이 개선
   - [ ] 엔티티 속성 구성 완전 추가
   - [ ] 1.19 Deep dark 관련
      - [ ] 비명체 워든 생성 범위 관련 구성 추가
      - [ ] 워든 익사 방지 구성 추가
- [ ] 자동 업데이트 추가
   - [ ] (메이저 버전 제외) 자동 버전업
   - [ ] (메이저 버전 포함) 자동 버전업
- [ ] server.properties 를 `config/` 폴더로 이전
- [ ] 게임 규칙 구성 파일 추가
